packages:
  - packages/*
  - playground
  - website
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.3.1+sha512-e3HjGx6AQ4dGCLu8ApbFMm49NYmJ/fiC2sptSyeQRsw94VjdfCYWF73i1pa2SlFqRmeHcrYCK7KsWYZlXX9m1A==
  "@savvy-web/pnpm-plugin-silk": 0.24.2+sha512-S+m0DmfxLj27auYOxLQW68WSOiLX1xbRJoLsWoqjlrLPfIGijArU2yhc5jTY412Sx41lY5Kugikhr29hgwyIXA==
linkWorkspacePackages: deep
verifyDepsBeforeRun: false
