packages:
  - packages/*
  - playground
  - website
autoInstallPeers: true
configDependencies:
  "@effected/pnpm-plugin-effect": 0.4.0+sha512-NAflOLRpoX/hgzZlaTi+XUKhz3wl5CL2C9S96T1Qx27mh7ridUA7pQmP3TUwlHmjGzP6dTzxGkVafaSLtHtGVQ==
  "@savvy-web/pnpm-plugin-silk": 0.26.1+sha512-1yWOOzo7sw4rFGYoXP7qgwzdnrQChWq1hPYr5bSLZQLICFJRPV0x3HbNgloWQg08AFZ2c54UlWpUjhrhFl6Dpw==
linkWorkspacePackages: deep
verifyDepsBeforeRun: false
