# Generated by pluginfinity. Do not edit.
_PF_TOOLS='Read=view
Bash=bash
Edit=edit
MultiEdit=edit
Write=create
Agent=task
Task=task
Grep=grep
Glob=glob
WebFetch=web_fetch
WebSearch=web_search
Skill=skill'
_PF_TOOLS_PLUGIN='vitest-agent'
_PF_TOOLS_MCP='{server}-{tool}'
_PF_TOOLS_SERVERS='mcp'
_PF_TOOLS_UNLISTED=unresolved
_PF_HAS_SKILLS='commit-cycle configuration configure coverage-improvement debugging decompose-goal-into-behaviors derive-test-name-from-behavior derive-test-shape-from-name interpret-test-failure operating-vitest-agent record-hypothesis-before-fix revert-on-extended-red run-and-classify setup tdd test-discovery verify-test-quality'
_PF_HAS_AGENTS='tdd-task'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS='mcp'
