/**
 * The pure halves of `registerStrictToolkit`: the served-schema
 * post-processing and the raw-payload unknown-key walk. `ping` / `help`
 * have no parameters, so the nested-object rule (issue #243) and the
 * discriminated-union rewrite are pinned here against synthetic schemas
 * generated by the same `Tool.getJsonSchema` the server uses.
 */

import { Schema } from "effect";
import { Tool } from "effect/unstable/ai";
import { describe, expect, it } from "vitest";
import { collectUnknownKeys, strictifyJsonSchema } from "../src/register-toolkit.js";

type JsonObject = Record<string, unknown>;

const served = (parameters: Schema.Top): JsonObject =>
	strictifyJsonSchema(Tool.getJsonSchema(Tool.make("t", { parameters })) as JsonObject);

const Nested = Schema.Struct({
	project: Schema.optionalKey(Schema.String),
	tags: Schema.optionalKey(
		Schema.Struct({
			all: Schema.optionalKey(Schema.Array(Schema.String)),
			any: Schema.optionalKey(Schema.Array(Schema.String)),
		}),
	),
	items: Schema.optionalKey(Schema.Array(Schema.Struct({ k: Schema.String }))),
});

const Discriminated = Schema.Union([
	Schema.Struct({ action: Schema.Literal("list"), project: Schema.optionalKey(Schema.String) }),
	Schema.Struct({ action: Schema.Literal("get"), id: Schema.Number }),
]);

const nonStrictObjectPaths = (node: unknown, path = "$", out: Array<string> = []): Array<string> => {
	if (node === null || typeof node !== "object") return out;
	const schema = node as JsonObject;
	if (schema.type === "object" && schema.properties !== undefined && schema.additionalProperties !== false) {
		out.push(path);
	}
	for (const [key, value] of Object.entries((schema.properties as JsonObject | undefined) ?? {})) {
		nonStrictObjectPaths(value, `${path}.${key}`, out);
	}
	for (const key of ["anyOf", "oneOf", "allOf", "prefixItems"]) {
		const branch = schema[key];
		if (Array.isArray(branch)) {
			for (const [i, b] of branch.entries()) nonStrictObjectPaths(b, `${path}[${key}:${i}]`, out);
		}
	}
	if (schema.items !== undefined) nonStrictObjectPaths(schema.items, `${path}[]`, out);
	return out;
};

describe("strictifyJsonSchema", () => {
	it("sets additionalProperties: false on every object node, nested and inside arrays", () => {
		const schema = served(Nested);
		expect(schema.additionalProperties).toBe(false);
		expect(nonStrictObjectPaths(schema)).toEqual([]);
	});

	it("leaves the Effect-emitted schema untouched otherwise", () => {
		const schema = served(Nested);
		expect(Object.keys(schema.properties as JsonObject)).toEqual(["project", "tags", "items"]);
		expect(schema.type).toBe("object");
	});

	it("rewrites a top-level action union to an object root with oneOf and x-discriminator", () => {
		const schema = served(Discriminated);
		expect(schema.type).toBe("object");
		expect(schema.anyOf).toBeUndefined();
		expect(schema["x-discriminator"]).toBe("action");
		expect(Array.isArray(schema.oneOf)).toBe(true);
		expect(nonStrictObjectPaths(schema)).toEqual([]);
	});

	it("does not rewrite a union whose members share no action/kind literal", () => {
		const schema = strictifyJsonSchema({
			anyOf: [{ type: "object", properties: { a: { type: "string" } } }, { type: "string" }],
		});
		expect(schema.type).toBeUndefined();
		expect(schema.anyOf).toHaveLength(2);
	});
});

describe("collectUnknownKeys", () => {
	it("accepts a payload that only carries declared keys", () => {
		expect(collectUnknownKeys({ project: "x", tags: { all: ["a"] }, items: [{ k: "v" }] }, served(Nested))).toEqual([]);
	});

	it("flags a top-level unknown key with the full accepted list", () => {
		expect(collectUnknownKeys({ project: "x", bogus: 1 }, served(Nested))).toEqual([
			{ path: [], unknown: ["bogus"], accepted: ["project", "tags", "items"] },
		]);
	});

	it("flags an unknown key inside a nested object (issue #243)", () => {
		expect(collectUnknownKeys({ tags: { anyy: ["a"] } }, served(Nested))).toEqual([
			{ path: ["tags"], unknown: ["anyy"], accepted: ["all", "any"] },
		]);
	});

	it("flags an unknown key inside an array element", () => {
		expect(collectUnknownKeys({ items: [{ k: "v" }, { k: "v", extra: true }] }, served(Nested))).toEqual([
			{ path: ["items", "1"], unknown: ["extra"], accepted: ["k"] },
		]);
	});

	it("checks a discriminated union against the branch the discriminant selects", () => {
		const schema = served(Discriminated);
		expect(collectUnknownKeys({ action: "list", project: "x" }, schema)).toEqual([]);
		expect(collectUnknownKeys({ action: "get", id: 1, project: "x" }, schema)).toEqual([
			{ path: [], unknown: ["project"], accepted: ["action", "id"] },
		]);
	});

	it("leaves an unmatched discriminant value to the schema decoder", () => {
		expect(collectUnknownKeys({ action: "nope", whatever: 1 }, served(Discriminated))).toEqual([]);
	});

	it("flags any key at all against an empty-params tool", () => {
		const schema = strictifyJsonSchema(Tool.getJsonSchema(Tool.make("t")) as JsonObject);
		expect(collectUnknownKeys({ bogus: 1 }, schema)).toEqual([{ path: [], unknown: ["bogus"], accepted: [] }]);
	});
});

const Identified = Schema.Struct({
	project: Schema.optionalKey(Schema.String),
}).annotate({ identifier: "IdentifiedParams" });

const IdentifiedUnion = Schema.Union([
	Schema.Struct({ action: Schema.Literal("list"), project: Schema.optionalKey(Schema.String) }).annotate({
		identifier: "ListParams",
	}),
	Schema.Struct({ action: Schema.Literal("get"), id: Schema.Number }).annotate({ identifier: "GetParams" }),
]);

describe("strictifyJsonSchema with $ref roots (identifier annotations)", () => {
	it("inlines a $ref root so an identified Struct serves as a strict object", () => {
		const raw = Tool.getJsonSchema(Tool.make("t", { parameters: Identified })) as JsonObject;
		expect(raw.$ref).toBe("#/$defs/IdentifiedParams");
		const schema = strictifyJsonSchema(raw);
		expect(schema.$ref).toBeUndefined();
		expect(schema.type).toBe("object");
		expect(schema.additionalProperties).toBe(false);
		expect(Object.keys(schema.properties as JsonObject)).toEqual(["project"]);
	});

	it("inlines $ref union members and rewrites the union to oneOf + x-discriminator", () => {
		const schema = served(IdentifiedUnion);
		expect(schema.type).toBe("object");
		expect(schema["x-discriminator"]).toBe("action");
		expect((schema.oneOf as Array<JsonObject>).every((m) => m.$ref === undefined && m.type === "object")).toBe(true);
		expect(nonStrictObjectPaths(schema)).toEqual([]);
	});

	it("rejects an unknown key in the branch an identified union selects", () => {
		const schema = served(IdentifiedUnion);
		expect(collectUnknownKeys({ action: "get", id: 1, project: "x" }, schema)).toEqual([
			{ path: [], unknown: ["project"], accepted: ["action", "id"] },
		]);
		expect(collectUnknownKeys({ action: "list", project: "x" }, schema)).toEqual([]);
	});
});
