# Generated by pluginfinity. Do not edit.
_PF_TOOLS=''
_PF_TOOLS_PLUGIN='vitest-agent'
_PF_TOOLS_MCP='mcp__plugin_{plugin}_{server}__{tool}'
_PF_TOOLS_SERVERS='mcp'
_PF_TOOLS_UNLISTED=keep
_PF_HAS_SKILLS='commit-cycle configuration configure coverage-improvement debugging decompose-goal-into-behaviors derive-test-name-from-behavior derive-test-shape-from-name interpret-test-failure operating-vitest-agent record-hypothesis-before-fix revert-on-extended-red run-and-classify setup tdd test-discovery verify-test-quality'
_PF_HAS_AGENTS='tdd-task'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS='mcp'
